version: "3.8"

services:
  user-service:
    build: ./UserService/server
    ports:
      - "4000:4000"
    env_file:
      - ./UserService/server/.env
    depends_on:
      - mysql
    networks:
      - backend
    restart: always

  mysql:
    image: mysql:8
    environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_DATABASE: tubeseai_userservice
    MYSQL_USER: root
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - backend
    restart: always

volumes:
  mysql-data:

networks:
  backend: