version: "3.8"

services:

  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: eai_project
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./mysql-init/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - backend
    restart: always

  history-service:
    build:
      context: .
    image: richolate/history-service:latest
    command: sh -c "/wait-for-it.sh mysql:3306 -- npm run dev"
    ports:
      - "5005:5005"
    depends_on:
      - mysql
    networks:
      - backend
    restart: always

volumes:
  mysql-data:

networks:
  backend: