version: '3.8'

services:
  payment-service:
    build: 
      context: .
    image: vregisyp/payment-service:latest
    command: sh -c "/wait-for-it.sh payment-db:3306 -- npm run dev"  # Changed mysql to payment-db
    container_name: payment-service
    ports:
      - "5004:5004"
    environment:
      DB_HOST: payment-db  # Changed mysql to payment-db
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: eai_project
      ORDER_SERVICE_URL: http://order-service:5004/graphql
    depends_on:
      - payment-db
    networks:
      - payment-network  # Add this line

  payment-db:
    image: mysql:8.0
    container_name: payment-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: eai_project
    ports:
      - "3306:3306"
    volumes:
      - payment-data:/var/lib/mysql
      - ./mysql-init/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - payment-network  # Add this line

volumes:
  payment-data:

networks:  # Add this section
  payment-network:
    driver: bridge