# Gunakan base image Node.js
FROM node:18-alpine

# Tentukan direktori kerja di dalam container
WORKDIR /usr/src/app

# Salin package.json dan package-lock.json
COPY package*.json ./

# Install semua dependencies
RUN npm install

# --- PERUBAHAN UTAMA DI SINI ---
# Salin semua file dari direktori saat ini (termasuk index.js) ke dalam container
COPY . .

# Beri tahu Docker bahwa container akan berjalan di port 5004
EXPOSE 5004

# Jalankan index.js yang sekarang berada di root direktori kerja
CMD [ "node", "index.js" ]