version: '3.8'
services:
  product-db:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: product_db
    ports:
      - "5434:5432"
    volumes:
      - product_data:/var/lib/postgresql/data

  product-service:
    build: .
    ports:
      - "5002:5002"
    depends_on:
      - product-db
    environment:
      DATABASE_URL: postgresql://user:pass@product-db:5432/product_db

volumes:
  product_data: